[tools]
bun = "latest"
claude = "latest"
eza = "0.23.4"
fd = "latest"
ffmpeg = "latest"
github-cli = "latest"
go = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
herdr = "latest"
imagemagick = "latest"
lua-language-server = "latest"
neovim = "nightly"
node = "lts"
oxfmt = "latest"
oxlint = "latest"
ripgrep = "latest"
ruff = "latest"
starship = "latest"
shfmt = "latest"
stylua = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
"aqua:quarylabs/sqruff" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:pyright" = "latest"
"npm:typescript" = "latest"
"npm:vscode-langservers-extracted" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
